import Link from "next/link";
import { ListChecks } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { EmptyState } from "@/components/ui/empty-state";
import { sql } from "@/lib/db";
import { requireProfile } from "@/lib/current-user";
import { formatDate, formatDateTime } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function AllReportsPage() {
  const profile = await requireProfile();

  const rows = await sql`
    SELECT
      r.id, r.period_start, r.period_end, r.status, r.completed_at,
      p.id AS project_id, p.code AS project_code, p.name AS project_name
    FROM report_runs r
    JOIN projects p ON p.id = r.project_id
    WHERE r.organisation_id = ${profile.organisation_id}
    ORDER BY r.completed_at DESC NULLS LAST
    LIMIT 100
  `;

  return (
    <>
      <PageHeader title="Report archive" description="Every weekly report generated by the platform." />
      {rows.length === 0 ? (
        <EmptyState icon={ListChecks} title="No reports generated yet" />
      ) : (
        <div className="table-wrap">
          <table className="table">
            <thead><tr><th>Project</th><th>Period</th><th>Status</th><th>Completed</th></tr></thead>
            <tbody>
              {rows.map((r: any) => (
                <tr key={r.id}>
                  <td><Link href={`/projects/${r.project_id}/reports`} className="card-link">{r.project_code}</Link></td>
                  <td>{formatDate(r.period_start)} – {formatDate(r.period_end)}</td>
                  <td className="capitalize">{r.status}</td>
                  <td>{formatDateTime(r.completed_at)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}
