import Link from "next/link";
import { ListChecks } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { EmptyState } from "@/components/ui/empty-state";
import { supabaseServer } from "@/lib/supabase/server";
import { formatDate, formatDateTime } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function AllReportsPage() {
  const sb = supabaseServer();
  const { data } = await sb.from("report_runs")
    .select("*, project:projects(id, code, name)")
    .order("completed_at", { ascending: false })
    .limit(100);

  return (
    <>
      <PageHeader title="Report archive" description="Every weekly report generated by the platform." />
      {!data?.length ? (
        <EmptyState icon={ListChecks} title="No reports generated yet" />
      ) : (
        <div className="table-wrap">
          <table className="table">
            <thead><tr><th>Project</th><th>Period</th><th>Status</th><th>Completed</th></tr></thead>
            <tbody>
              {(data as any[]).map((r) => (
                <tr key={r.id}>
                  <td><Link href={`/projects/${r.project?.id}/reports`} className="text-brand-700 hover:underline">{r.project?.code}</Link></td>
                  <td>{formatDate(r.period_start)} – {formatDate(r.period_end)}</td>
                  <td className="capitalize">{r.status}</td>
                  <td className="text-slate-600">{formatDateTime(r.completed_at)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}
